import { Heart, MapPin, UserPlus, X, Zap } from "lucide-react";
import { useState } from "react";
import { apiClient } from "../api/client";
import { useWorldStore } from "./worldStore";

export function ProfilePanel({ demoMode }: { demoMode: boolean }) {
  const selected=useWorldStore((s)=>s.selected);const select=useWorldStore((s)=>s.select);const teleportTo=useWorldStore((s)=>s.teleportTo);const [following,setFollowing]=useState(false);const [favorite,setFavorite]=useState(false);const [pending,setPending]=useState(false);
  if(!selected)return null;const building=selected;const live=!building.id.startsWith("demo-")&&!demoMode;
  async function action(kind:"follow"|"favorite"){if(!live)return;setPending(true);try{if(kind==="follow"){if(following)await apiClient.delete(`/users/${building.ownerId}/follow`);else await apiClient.post(`/users/${building.ownerId}/follow`);setFollowing(!following);}else{if(favorite)await apiClient.delete(`/buildings/${building.id}/favorite`);else await apiClient.post(`/buildings/${building.id}/favorite`);setFavorite(!favorite);}}finally{setPending(false);}}
  function teleport(){teleportTo(building.x,building.z);select(null);}
  return <aside className="profile-panel" aria-label={`Building profile for ${selected.username}`}><button className="panel-close" aria-label="Close profile" onClick={()=>select(null)}><X size={17}/></button><div className="profile-avatar">{selected.displayName.slice(0,2).toUpperCase()}<span className={selected.online?"online":""}/></div><div className="eyebrow"><span/> {selected.online?"Online now":selected.district}</div><h2>{selected.displayName}</h2><p>@{selected.username}</p><div className="profile-stats"><span><strong>{selected.followerCount?.toLocaleString()??"Private"}</strong> followers · height</span><span><strong>{selected.followingCount?.toLocaleString()??"Private"}</strong> following · footprint</span><span><strong>{selected.level}</strong> building level</span></div><div className="panel-actions"><button disabled={!live||pending} onClick={()=>void action("follow")}><UserPlus size={16}/>{following?"Unfollow":"Follow"}</button><button disabled={!live||pending} onClick={()=>void action("favorite")}><Heart size={16} fill={favorite?"currentColor":"none"}/>{favorite?"Saved":"Favorite"}</button><button onClick={teleport}><Zap size={16}/>Take me there</button></div><div className="building-location"><MapPin size={14}/> Sir MVIT Campus · {selected.style}</div>{!live&&<small className="demo-note">Social actions are disabled for offline demo buildings.</small>}</aside>;
}
