import { PrismaClient,BuildingStyle,District,UserRole } from "@prisma/client";
import argon2 from "argon2";

const prisma=new PrismaClient();
const first=["Maya","Arjun","Nora","Leo","Aisha","Kenji","Iris","Omar","Sofia","Mateo","Zara","Theo"];
const last=["Chen","Vale","Pixel","Rhodes","Khan","Sato","Bloom","Noor","Reyes","Silva","Hart","Nova"];
const districts=Object.values(District);const interests=["typescript","design","gaming","music","photography","fitness","open source","3d art","webgl","community"];
const achievements=[{slug:"first-steps",name:"First Steps",description:"Explore your first district.",iconAsset:"compass",points:10},{slug:"explorer",name:"Explorer",description:"Visit 25 buildings.",iconAsset:"map",points:25},{slug:"social-starter",name:"Social Starter",description:"Gain your first follower.",iconAsset:"users",points:10},{slug:"city-explorer",name:"City Explorer",description:"Visit every district.",iconAsset:"city",points:75},{slug:"night-owl",name:"Night Owl",description:"Explore the city at night.",iconAsset:"moon",points:20}];
async function main(){const passwordHash=await argon2.hash("SocialVerse7Demo!",{type:argon2.argon2id});for(const achievement of achievements)await prisma.achievement.upsert({where:{slug:achievement.slug},update:achievement,create:achievement});const users=[];for(let index=0;index<180;index++){const username=`${first[index%first.length]!.toLowerCase()}_${last[(index*7)%last.length]!.toLowerCase()}_${String(index+1).padStart(3,"0")}`;const district=districts[index%districts.length]!;const x=((index%18)-9)*26;const z=(Math.floor(index/18)-5)*28+(Math.floor(index/18)>=5?55:-55);const user=await prisma.user.upsert({where:{username},update:{},create:{email:`${username}@socialverse.demo`,username,passwordHash,role:index===0?UserRole.ADMIN:UserRole.USER,profile:{create:{displayName:`${first[index%first.length]} ${last[(index*7)%last.length]}`,bio:`Building ideas and meeting people in the ${district.toLowerCase()} district.`,district,interests:[interests[index%interests.length]!,interests[(index+3)%interests.length]!,interests[(index+6)%interests.length]!]}},privacy:{create:{}},building:{create:{district,x,z,chunkX:Math.floor(x/128),chunkZ:Math.floor(z/128),level:1+index%12,style:index%17===0?BuildingStyle.SKYSCRAPER:index%7===0?BuildingStyle.TOWER:index%3===0?BuildingStyle.APARTMENT:BuildingStyle.HOUSE,customization:{create:{theme:index%2?"AURORA":"MIDNIGHT",billboardText:`Welcome to ${first[index%first.length]}'s place`}}}}},select:{id:true}});users.push(user.id);}const follows=[];for(let i=0;i<users.length;i++){const count=3+(i*13)%30;for(let offset=1;offset<=count;offset++)follows.push({followerId:users[i]!,followingId:users[(i+offset*7)%users.length]!});}await prisma.follow.createMany({data:follows.filter((row)=>row.followerId!==row.followingId),skipDuplicates:true});const now=new Date();await prisma.worldState.upsert({where:{id:"primary"},update:{},create:{id:"primary",weather:"CLEAR",weatherSeed:42}});for(let i=0;i<30;i++)await prisma.trendingSnapshot.upsert({where:{userId_windowStartedAt:{userId:users[i]!,windowStartedAt:new Date(now.getTime()-86_400_000)}},update:{},create:{userId:users[i]!,score:100-i*2+(i%5)*7,followerGrowth:30-i%12,profileVisits:200-i*3,interactions:80+i,activityScore:50+i%10,windowStartedAt:new Date(now.getTime()-86_400_000)}});console.log(`Seeded ${users.length} SocialVerse citizens. Demo password: SocialVerse7Demo!`);}
main().catch((error)=>{console.error(error);process.exitCode=1;}).finally(()=>prisma.$disconnect());
