import { prisma } from "../../database/prisma.js";
import { AppError } from "../../utils/app-error.js";

export const platformService={
  async dashboard(userId:string){const [user,recentFollowers,favorites,notifications]=await prisma.$transaction([prisma.user.findUnique({where:{id:userId},include:{profile:true,building:true,achievements:{include:{achievement:true},orderBy:{unlockedAt:"desc"},take:8},_count:{select:{followsReceived:true,followsGiven:true}}}}),prisma.follow.findMany({where:{followingId:userId},orderBy:{createdAt:"desc"},take:8,include:{follower:{include:{profile:true}}}}),prisma.favorite.findMany({where:{userId},orderBy:{createdAt:"desc"},take:8,include:{building:{include:{user:{include:{profile:true}}}}}}),prisma.notification.findMany({where:{recipientId:userId},orderBy:{createdAt:"desc"},take:8})]);if(!user?.profile||!user.building)throw new AppError(404,"USER_NOT_FOUND","Account not found.");return{profile:user.profile,followers:user._count.followsReceived,following:user._count.followsGiven,building:{id:user.building.id,level:user.building.level,visits:user.building.visitCount,style:user.building.style},recentFollowers:recentFollowers.map((r)=>({id:r.follower.id,username:r.follower.username,displayName:r.follower.profile!.displayName})),favorites:favorites.map((f)=>({id:f.building.id,username:f.building.user.username,displayName:f.building.user.profile!.displayName})),achievements:user.achievements,notifications};},
  async interior(buildingId:string,viewerId?:string){const building=await prisma.building.findUnique({where:{id:buildingId},include:{user:{include:{profile:true,privacy:true,posts:{orderBy:{createdAt:"desc"},take:24},achievements:{include:{achievement:true}},_count:{select:{followsReceived:true,followsGiven:true}}}},customization:true}});if(!building||!building.user.profile)throw new AppError(404,"BUILDING_NOT_FOUND","Building not found.");if(!building.user.privacy?.allowBuildingVisits&&viewerId!==building.userId)throw new AppError(403,"BUILDING_VISITS_DISABLED","This interior is private.");return{template:building.style,customization:building.customization,owner:{username:building.user.username,displayName:building.user.profile.displayName,bio:building.user.profile.bio,avatarUrl:building.user.profile.avatarUrl,interests:building.user.profile.interests,followers:building.user._count.followsReceived,following:building.user._count.followsGiven},posts:building.user.posts,achievements:building.user.achievements.map((a)=>({...a.achievement,unlockedAt:a.unlockedAt}))};},
  achievements:()=>prisma.achievement.findMany({orderBy:{points:"asc"}}),
  userAchievements:(userId:string)=>prisma.userAchievement.findMany({where:{userId},include:{achievement:true},orderBy:{unlockedAt:"desc"}}),
};
